// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: session.proto

#include "session.pb.h"
#include "session.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace session {

static const char* Greeter_method_names[] = {
  "/session.Greeter/SayHello",
  "/session.Greeter/SessionInfor",
};

std::unique_ptr< Greeter::Stub> Greeter::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Greeter::Stub> stub(new Greeter::Stub(channel, options));
  return stub;
}

Greeter::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SayHello_(Greeter_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SessionInfor_(Greeter_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status Greeter::Stub::SayHello(::grpc::ClientContext* context, const ::session::Request& request, ::session::Reply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::session::Request, ::session::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SayHello_, context, request, response);
}

void Greeter::Stub::async::SayHello(::grpc::ClientContext* context, const ::session::Request* request, ::session::Reply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::session::Request, ::session::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, std::move(f));
}

void Greeter::Stub::async::SayHello(::grpc::ClientContext* context, const ::session::Request* request, ::session::Reply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::session::Reply>* Greeter::Stub::PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::session::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::session::Reply, ::session::Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SayHello_, context, request);
}

::grpc::ClientAsyncResponseReader< ::session::Reply>* Greeter::Stub::AsyncSayHelloRaw(::grpc::ClientContext* context, const ::session::Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSayHelloRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::session::SessionReply>* Greeter::Stub::SessionInforRaw(::grpc::ClientContext* context, const ::session::Request& request) {
  return ::grpc::internal::ClientReaderFactory< ::session::SessionReply>::Create(channel_.get(), rpcmethod_SessionInfor_, context, request);
}

void Greeter::Stub::async::SessionInfor(::grpc::ClientContext* context, const ::session::Request* request, ::grpc::ClientReadReactor< ::session::SessionReply>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::session::SessionReply>::Create(stub_->channel_.get(), stub_->rpcmethod_SessionInfor_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::session::SessionReply>* Greeter::Stub::AsyncSessionInforRaw(::grpc::ClientContext* context, const ::session::Request& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::session::SessionReply>::Create(channel_.get(), cq, rpcmethod_SessionInfor_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::session::SessionReply>* Greeter::Stub::PrepareAsyncSessionInforRaw(::grpc::ClientContext* context, const ::session::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::session::SessionReply>::Create(channel_.get(), cq, rpcmethod_SessionInfor_, context, request, false, nullptr);
}

Greeter::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::session::Request, ::session::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::session::Request* req,
             ::session::Reply* resp) {
               return service->SayHello(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< Greeter::Service, ::session::Request, ::session::SessionReply>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::session::Request* req,
             ::grpc::ServerWriter<::session::SessionReply>* writer) {
               return service->SessionInfor(ctx, req, writer);
             }, this)));
}

Greeter::Service::~Service() {
}

::grpc::Status Greeter::Service::SayHello(::grpc::ServerContext* context, const ::session::Request* request, ::session::Reply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::SessionInfor(::grpc::ServerContext* context, const ::session::Request* request, ::grpc::ServerWriter< ::session::SessionReply>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace session

